# Generated by Django 6.0.5 on 2026-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('payment_success', 'Payment Success'), ('new_message', 'New Message'), ('new_vehicle', 'New Vehicle Added')], max_length=50),
        ),
    ]
